- hosts: appsvrs
  tasks: 
    - name: Install centos-release-scl
      yum:
       pkg: centos-release-scl
       state: present
       update_cache: true
      become: true
    - name: install python
      yum:
       pkg: rh-python36
       state: present
       update_cache: true
      become: true
    - name: run bash command
      shell: scl enable rh-python36 bash
      become: true
